### ISSUE TITLE
Please add support for API keys

### ISSUE THREAD

**Issue by zabela** [apigee/apigee-deploy-maven-plugin#116]
Using this plugin, one is able to create/update the developer apps and its attributes but it is not currently possible to create/update the apikeys.

Also, using this plugin it is not possible to link the apis products with apikeys. Whenever we are specifying the api products in JSON file, it is creating new credentials for that particular app during deployment. 

For apigee configuration deployment, keeping the apigee config options as 'update' - which should update the existing ones, instead of creating new credentials - does not seem to be not working as expected.

Thus, is it possible to provide support to apikeys so that one can deploy apigee apps along with them and api products?

**Comment by ssvaidyanathan** [comment]
@zabela - you have opened the issue in the wrong repo. Please open config plugin issues [here](https://github.com/apigee/apigee-config-maven-plugin/issues/new). 

I guess there is already an [issue](https://github.com/apigee/apigee-config-maven-plugin/issues/17) opened similar to what you have raised

Since this is the deploy plugin, am closing this issue

**Comment by zabela** [comment]
Hi @ssvaidyanathan, thanks for forwarding me to the right repo.
This issue is actually a different one than the one you linked. 
Could you remove the linkage?
I will create a new one on that repo.

**Comment by zabela** [comment]
Here the new [one](https://github.com/apigee/apigee-config-maven-plugin/issues/70). Could you link that one instead?

**Comment by ssvaidyanathan** [comment]
Got it. thanks
Good feature to include. Lets discuss it on the issue you opened.
