### ISSUE TITLE
Is there any plan to add the sharedflows in the configuration tokens

### ISSUE THREAD

**Issue by gbansal3** [apigee/apigee-deploy-maven-plugin#118]
In our project we are using maven plugin to configure and deploy the shared flows, but from environment to environment there is a difference in the policy the shared flow is expected to refer to. In case of proxies we are able to handle that by using config.json to update the name of policy during deployment, but as shared flows are not part of config tokens like proxies/targets we are not able to achieve that rather we have to create two separate shared flows for two environments which is like repetition of almost 80-85% code in the two repositories.

**Comment by ssvaidyanathan** [comment]
Thanks for opening this @gbansal3 
Can you please share an example, so that I can check

**Comment by gbansal3** [comment]
Example in case of API Proxy:
My Proxy File is like: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ProxyEndpoint name="default">...
    <PreFlow name="PreFlow">
        <Request>			
			<Step>
				<Name>IP_VERIFY_POLICY</Name>
			</Step>
.....</ProxyEndpoint>
Config File has following to give different policy references to this check on different environments.
"xpath": "/ProxyEndpoint/PreFlow/Request/Step[Name = 'IP_VERIFY_POLICY']/Name",
"value": "AC_Ipcheck_dummy"

Now if I need to create a shared flow to replace this and other policies in the proxy, I need to create different shared flows for different environment, as config.json has no support for modifying content of default.xml file present in sharedflows folder.

**Comment by ssvaidyanathan** [comment]
Thanks for clarifying that. 

In your case you will have different policies for different environment in your "policies" directory but only use one of them during build time? Is this correct ?

If the above is correct - why not have all the policies and execute based on environment ? Just a thought ? 
```xml
<Request>
  <Step>
    <Name>IP_VERIFY_POLICY-DEV</Name>
    <Condition>environment.name == "dev"</Condition>
  </Step>
  <Step>
    <Name>IP_VERIFY_POLICY-QA</Name>
    <Condition>environment.name == "qa"</Condition>
  </Step>
</Request>
```
That should do the trick. I know the code could get big if you have this around multiple policies? If this was specific to Access Control policy, you can also use a variable to execute it. For example,
```xml
<AccessControl name="ACL">
  <IPRules noRuleMatchAction = "ALLOW">
    <MatchRule action = "DENY">
      <SourceAddress mask="{kvm.mask.value}">{kvm.ip.value}</SourceAddress>
    </MatchRule>
    </IPRules>
</AccessControl>
```

In that case, you can have the configuration in an ENV scoped KVM and then read and execute with that. So the same single policy will do the trick for you. You just need a KVM lookup before the actual Access Control policy.

However, the main issue you raised is a good enhancement to have. What I have provided are basically better options to tackle it instead of multiple sharedflows you were planning to create.

**Comment by ssvaidyanathan** [comment]
v1.2. and later support this
