### ISSUE TITLE
Any mvn goal(s) to deploy lower env revision to upper env ??

### ISSUE THREAD

**Issue by sithik4git** [apigee/apigee-deploy-maven-plugin#188]
I want to promote/deploy Staging proxy revision to Production in Apigee Edge Cloud platform.
I could see it is possible by getting the deployed revision number from Staging and deploy the same to Production using API Management requests.

GET https://api.enterprise.apigee.com/v1/organizations/{org_name}/environments/{env_name}/apis/{api_name}/deployments
POST https://api.enterprise.apigee.com/v1/organizations/{org_name}/environments/{env_name}/apis/{api_name}/revisions/{revision_number}/deployments

 but it requires custom script.

Before jumping into that stuff, I just want to check whether there is any mvn goal in the current apigee-deploy-maven-plugin version that supports above functionality.

I am open for other suggestions as well!!!

Thanks,
Mohamed Sithik

**Comment by ssvaidyanathan** [comment]
HI @sithik4git 
You are right  - the plugin does not support that. The purpose of the plugin is to package the code from your source code and then deploy that to Apigee

I would always recommend doing that so that you have two different versions of the same proxy running and you can control the changes too. Usually you have two different branches/tags from where these deployments happen so many use the plugin to push code from the appropriate branches. If thats not the case for you, you will need to write the custom script by calling the Management API directly. 

Since this is working as expected, I will close this issue.

**Comment by sithik4git** [comment]
Thanks for the reply, @ssvaidyanathan . I will look other options to achieve my need.
Thanks again.
