### ISSUE TITLE
Support for property sets in Apigee X

### ISSUE THREAD

**Issue by otheriault** [apigee/apigee-deploy-maven-plugin#191]
It would be really great to be able to also support property sets in the maven plugin. The files are `.property` files and this could be well managed in the same repository as the proxies and shared flows to enable gitOps for the property sets.

**Comment by ssvaidyanathan** [comment]
@otheriault - Since these are resource files, you should be able to configure them using the [apigee-config-maven-plugin](https://github.com/apigee/apigee-config-maven-plugin). Check out [this](https://github.com/apigee/apigee-config-maven-plugin/tree/hybrid/samples/EdgeConfig) sample. It has the `resourceFiles` directory with the properties files and in the [resourcefiles.json](https://github.com/apigee/apigee-config-maven-plugin/blob/hybrid/samples/EdgeConfig/resources/edge/env/test/resourcefiles.json), we refer to the property file. The plugin will do the needful. 

Marking this as closed as its already available. Please open an issue in the other repo if you still face any problem

**Comment by otheriault** [comment]
Thank you, I will look to the other plugin.
