### ISSUE TITLE
Issue while deploying bundle using maven plugin

### ISSUE THREAD

**Issue by basavarajdhanashetti** [apigee/apigee-deploy-maven-plugin#40]
Hi,

I have created a maven application for building and deploying api bundle. Followed steps given in document. I am facing below issues. Can someone help please...?
1. Deploying new proxy: If I am deploying proxy for the first time (that means there is no existing proxy available Apigee Edge). Apigee api web link returns error message as below:

---

GET  https://api.enterprise.apigee.com/v1/organizations/bdhanashetti/apis/json-formatter/deployments
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[ERROR] 404 Not Found
{
  "code" : "messaging.config.beans.ApplicationDoesNotExist",
  "message" : "APIProxy named json-formatter does not exist in organization bdhanashetti",
  "contexts" : [ ]
## }
1. Since I am facing above error, I have imported the ZIP file using UI application (this works wonderfully !!!). Then I have gone for re-deployment using maven deploy command. This command corrupts the proxy link. Error on proxy link says there is no revision attached to it (as shown in below image).

![image](https://cloud.githubusercontent.com/assets/13515851/8950473/a837aaec-35df-11e5-9641-e0e1be2c15a0.png)

Here is link for the test project (https://github.com/basavarajdhanashetti/mands) for review.

Thanks,
Basavaraj

**Comment by ssvaidyanathan** [comment]
HI @basavarajdhanashetti 

I know this issue was opened a while back. Sorry to get back this late. I looked at your repo. Please make the following changes to your [pom.xml](https://github.com/basavarajdhanashetti/mands/blob/master/pom.xml)

Please change line number 127 to `<apigee.options>update</apigee.options>`

update will create or update an existing proxy

Also please add the following t0 [pom.xml](https://github.com/basavarajdhanashetti/mands/blob/master/json-formatter/pom.xml)
after line 90
```xml
<!--deploy bundle -->
<execution>
    <id>deploy-bundle-step</id>
        <phase>install</phase>
        <goals>
             <goal>deploy</goal>
        </goals>
 </execution>
```
This will include the deploy as well. Once you have made these change, just run

`mvn clean install -Ptest -Dusername=abc -Dpassword=something`

This should work. Worked for me.

NOTE: You can also update the plugin version you are using. I see you have used 1.0.0, the latest is 1.1.5

**Comment by ssvaidyanathan** [comment]
No update - hence closing the issue
