### ISSUE TITLE
Rollback MOJO

### ISSUE THREAD

**Issue by thejibz** [apigee/apigee-deploy-maven-plugin#84]
Hello,

In a CI/CD context, I need to be able to make a rollback if some tests fails, nothing crazy :)
Currently, these are the mojo availables: clean, update, overwrite, validate

**So I propose that a new mojo get introduced: rollback**
It will basicaly make a clean of the N (last) revision and deploy the N-1 revision.

I will make a pull request as soon I have my code working.

Cheers.

**Comment by ssvaidyanathan** [comment]
Hi @thejibz 

Thanks for raising this. This has been a topic that was in discussion couple of times. The issue with this is that - you never know if the previous revision (N-1) is the correct revision to go to. It is possible that the previous revision also had issues for which you are deploying a new revision. Rolling back to that again would cause failures. Hence we did not include that option on purpose.

The other reason why we did not include that is - we want the CI/CD pipeline to include tests and their failure should break the build. As a rollback, we trigger the same CI/CD pipeline with the stable branch that was stable prior to this new push. With this everything is audited and is going from the SCM. 

Also the main reason for this plugin to package code and deploy from SCM. If you really wanted to do a rollback, you can always do that using the Management API.

Hope this clarifies. I am happy to discuss in detail. We can continue the dialogue here so that its all tracked and useful for others if they are looking for similar request.

Tagging @msadasivam as well

**Comment by thejibz** [comment]
Hi @ssvaidyanathan 

Thank you for your detailled answer ! I understand why you doesn't want the "rollback" option. It makes sense to rely on the SCM as the source of truth.

However, I add this need for a small project and I told myself why not contribute the feature ;)
In any case, I wont take offense if the pull request is refused, as I said I understand.
#85

**Comment by ssvaidyanathan** [comment]
Thanks for understanding.. will close the PR as well
